name: run discord bot

# on:
#   schedule:
#     - cron: "0 0 * * *"  # utc time
jobs:
  cron:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: yarn install --prefer-offline

      - name: Generate Environment Variables File
        run: |
          echo "TOKEN=$TOKEN" >> .env
          echo "CLIENTID=$CLIENTID" >> .env
          echo "GUILDID=$GUILDID" >> .env
          echo "CHANNELID=$CHANNELID" >> .env
          echo "ORG=$ORG" >> .env
          echo "AUTH_TOKEN=$AUTH_TOKEN" >> .env
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CLIENTID: ${{ secrets.CLIENTID }}
          GUILDID: ${{ secrets.GUILDID }}
          CHANNELID: ${{ secrets.CHANNELID }}
          ORG: ${{ secrets.ORG }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}

      - name: Run bot
        run: yarn serve   # TODO: 봇을 항상 키는 게 아니라 메시지만 전송하도록 해야함
